In [1]:
import petrovisor as pv

# Authorization

In [ ]:
# url
discovery_url = r'https://identity.us1.petrovisor.com'
# workspace
workspace = 'Workspace Name'

# generate access key (only for the first time, comment the line afterwards)
key = pv.PetroVisor.generate_credentials_key()
# print(f"key : '{key}'")
# save key for later to reuse
# key = ''

api = pv.PetroVisor(workspace = workspace, discovery_url = discovery_url, key = key)
print(api.Api)

https://api.us1.pvaws.petrovisor.com

# PetroVisor API Swagger

https://api.us1.petrovisor.com/index.html

# Examples: Pivot Tables

In [3]:
# get existing pivot table names
api.get_pivot_table_names()

["2025 Feb - What's New",
 '2222',
 'aaaaaer',
 'all types of entities',
 'anna data view',
 'anna ddd',
 'anna depth 2025',
 'anna depth 2026',
 'anna depth pivot 2025',
 'anna depth static',
 'anna depth string',
 'anna depth string 2025',
 'anna new',
 'anna static',
 'anna string',
 'anna test',
 'anna test new',
 'anna time depth',
 'ARUN-SAWOCS',
 'Commodity Prices',
 'Company Performance Financials',
 'Company Performance Production and Forecast Rates',
 'depth',
 'depth 1',
 'Depth random data',
 'Economic Inputs',
 'Economics Static Data',
 'Economics String Data',
 'Economics Time Data',
 'first data pivot',
 'Hub Prices and Fractions',
 'j319',
 'jeet-gen-test',
 'jeet-generate-test',
 'jeet-new-table-test',
 'jeet-public-test',
 'jeet-test',
 'Jessica # Waste',
 'Jessica - Data Table 2',
 'Jessica - Data View',
 'Jessica - Data View Table',
 'Jessica - Private Well Names',
 'Jessica Append Testing',
 'Jessica Append Testing 2',
 'Jessica Longitude',
 'Jessica Static',
 'Jessica Waste',
 'Jessica Waste 2',
 'Jessica Waste 3',
 'Jessica Waste 4',
 'Jessica Well Names',
 'Jessica Well Names 2',
 "Josh's cool table",
 'JTest',
 'kenton',
 'Kenton Test',
 'Kenton2',
 'Kenton3',
 'Knowledge Base Example',
 'New table',
 'New table 2 the sequal',
 'Refresh Report Visualization - Monthly Data',
 'rrr',
 "Single'Mark",
 "ss'hh",
 'Table-Skip-Empty-Row-Test',
 'test',
 'Test parse',
 'test-jeet',
 'test-jeet-ipetrovisor-props',
 'test-jeet-ipetrovisor-props-fixed',
 'test-jeet-ipetrovisor-props2',
 'test-jeet-ipetrovisor-props3',
 'test-jeet-user-prop',
 'test2',
 'test4',
 'test6',
 'testb zzuuuuu',
 'testing save',
 'Testing save and gen',
 'Testing save and gen 1',
 'Testing Tables with Spaces    ',
 'text static pivot',
 'tommy delete',
 'tommy test 1111 data view',
 'tommy test 3 wells',
 'tommy test pivot table',
 'undefined.$$',
 'vsdy',
 '_static_with_empty_rows']

In [4]:
pivot_table_name = 'Iris Pivot Table'
entity_set = 'Iris Flowers' # override EntitySet, use None to use EntitySet from PivotTable definition
scope = 'Iris Flowers Scope' # override Scope, use None to use Scope from PivotTable definition

In [5]:
# load pivot table data (generated)
api.load_pivot_table_data(pivot_table_name,
                             entity_set=entity_set,
                             scope=scope,
                             generate=True)

,Entity,Time,petal length (cm),petal width (cm),sepal length (cm),sepal width (cm),flower ( )
0,Iris,1992-01-01,1.4,0.2,5.1,3.5,1
1,Iris,1992-01-02,1.4,0.2,4.9,3.0,1
2,Iris,1992-01-03,1.3,0.2,4.7,3.2,1
3,Iris,1992-01-04,1.5,0.2,4.6,3.1,1
4,Iris,1992-01-05,1.4,0.2,5.0,3.6,1
...,...,...,...,...,...,...,...
145,Iris,1992-05-25,5.2,2.3,6.7,3.0,3
146,Iris,1992-05-26,5.0,1.9,6.3,2.5,3
147,Iris,1992-05-27,5.2,2.0,6.5,3.0,3
148,Iris,1992-05-28,5.4,2.3,6.2,3.4,3
149,Iris,1992-05-29,5.1,1.8,5.9,3.0,3

In [6]:
# save pivot table data
api.save_pivot_table_data(pivot_table_name,
                             entity_set=entity_set,
                             scope=scope)

In [7]:
# load pivot table data (saved)
api.load_pivot_table_data(pivot_table_name)

,Entity,Time,petal length (cm),petal width (cm),sepal length (cm),sepal width (cm),flower ( )
0,Iris,1992-01-01,1.4,0.2,5.1,3.5,1
1,Iris,1992-01-02,1.4,0.2,4.9,3.0,1
2,Iris,1992-01-03,1.3,0.2,4.7,3.2,1
3,Iris,1992-01-04,1.5,0.2,4.6,3.1,1
4,Iris,1992-01-05,1.4,0.2,5.0,3.6,1
...,...,...,...,...,...,...,...
145,Iris,1992-05-25,5.2,2.3,6.7,3.0,3
146,Iris,1992-05-26,5.0,1.9,6.3,2.5,3
147,Iris,1992-05-27,5.2,2.0,6.5,3.0,3
148,Iris,1992-05-28,5.4,2.3,6.2,3.4,3
149,Iris,1992-05-29,5.1,1.8,5.9,3.0,3

In [8]:
# delete pivot table data
api.delete_pivot_table_data(pivot_table_name)