In [16]:
import petrovisor as pv
from petrovisor import ItemType, RefTableColumnType

In [17]:
import os
import time
import psutil
import pandas as pd
import numpy as np

# Authorization

In [ ]:
# url
discovery_url = r'https://identity.us1.petrovisor.com'
# workspace
workspace = 'Workspace Name'

# generate access key (only for the first time, comment the line afterwards)
key = pv.PetroVisor.generate_credentials_key()
# print(f"key : '{key}'")
# save key for later to reuse
# key = ''

api = pv.PetroVisor(workspace = workspace, discovery_url = discovery_url, key = key)
print(api.Api)

https://api.us1.pvaws.petrovisor.com

# PetroVisor API Swagger

https://api.us1.petrovisor.com/index.html

# Examples: RefTables

#### Create DataFrame

In [19]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# get dataframe size
def dataframe_size(df):
    return df.memory_usage(deep=True).sum()/1024/1024 # MB

# get memory size used by process
def process_size():
    process = psutil.Process(os.getpid())
    return process.memory_info().rss/1024/1024 # MB

# Keep your existing row count configuration
num_rows = int(1000)
columns = list('ABCDEF')

# Create the initial DataFrame
df = pd.DataFrame(np.random.uniform(0,1,size=(num_rows, len(columns))), columns=columns)
df_size = dataframe_size(df)
memory_size = process_size()

# Entity column (keeping your existing logic)
df['Entity'] = None
df.loc[:num_rows//2, 'Entity'] = 'Well 001'

# Generate time series data with some gaps
start_date = datetime(2025, 1, 1)  # Starting from January 1st, 2025
time_interval = timedelta(hours=1)  # 1-hour interval

# Create base time series
time_series = [start_date + i * time_interval for i in range(num_rows)]

# Introduce random gaps (None values) in about 10% of the data
time_series = np.array(time_series, dtype=object)
gap_indices = np.arange(9, num_rows, 10)  # Creates gaps at every 10th position (0-based)
time_series[gap_indices] = None

# Assign the time series to the DataFrame
df['Time'] = time_series

# Key column
df['Key'] = [i for i in range(0,len(df))]

# Reorder columns and rename
df = df[['Entity','Time','Key',*columns]]
df = df.rename(columns={"F": "F [cm]", "E": "E [ft]"})

print(f"Memory used: {memory_size} MB")
print(f"DataFrame Shape: {df.shape}")
print("\nSample of the data:")
display(df.head())

# Additional information about the time series
non_null_times = df['Time'].count()
print(f"\nTime series statistics:")
print(f"Total rows: {len(df)}")
print(f"Non-null times: {non_null_times}")
print(f"Null times: {len(df) - non_null_times}")
print(f"Time range: {df['Time'].min()} to {df['Time'].max()}")

Memory used: 144.921875 MB
DataFrame Shape: (1000, 9)

Sample of the data:

,Entity,Time,Key,A,B,C,D,E [ft],F [cm]
0,Well 001,2025-01-01 00:00:00,0,0.758688,0.259537,0.015066,0.232888,0.722988,0.213938
1,Well 001,2025-01-01 01:00:00,1,0.540870,0.711250,0.526099,0.787087,0.112297,0.186608
2,Well 001,2025-01-01 02:00:00,2,0.028996,0.039536,0.946708,0.910372,0.516418,0.271480
3,Well 001,2025-01-01 03:00:00,3,0.495759,0.232222,0.594412,0.694344,0.361668,0.835050
4,Well 001,2025-01-01 04:00:00,4,0.398229,0.301194,0.508277,0.872429,0.015576,0.204858

Time series statistics:
Total rows: 1000
Non-null times: 900
Null times: 100
Time range: 2025-01-01 00:00:00 to 2025-02-11 14:00:00

## Add RefTable

In [20]:
name = 'PyRefTable'

In [21]:
# delete data if exists
api.delete_ref_table_data(name)
api.delete_ref_table(name)

In [22]:
# add new table

start_time = time.time()

api.add_ref_table(name, df, description = 'Testing API from Python')

end_time = time.time()
print(f"Elapsed time: {(end_time-start_time)/60}")

Elapsed time: 0.2677892804145813

In [23]:
# add data to already existing table

start_time = time.time()

api.add_ref_table(name, df, description = 'Testing API from Python')

end_time = time.time()
print(f"Elapsed time: {(end_time-start_time)/60}")

Elapsed time: 0.1257750391960144

In [24]:
# get data info
api.get_ref_table_data_info(name)

{'Key': {'ColumnType': 'Numeric', 'UnitName': ' ', 'Name': 'Key'},
 'Values': [{'ColumnType': 'Numeric', 'UnitName': ' ', 'Name': 'A'},
  {'ColumnType': 'Numeric', 'UnitName': ' ', 'Name': 'B'},
  {'ColumnType': 'Numeric', 'UnitName': ' ', 'Name': 'C'},
  {'ColumnType': 'Numeric', 'UnitName': ' ', 'Name': 'D'},
  {'ColumnType': 'Numeric', 'UnitName': 'ft', 'Name': 'E'},
  {'ColumnType': 'Numeric', 'UnitName': 'cm', 'Name': 'F'}],
 'Modified': '2026-06-28T18:34:27.3903017Z',
 'Created': '2026-06-28T18:34:11.344Z',
 'ModifiedBy': 'rmanasipov',
 'CreatedBy': 'rmanasipov',
 'Description': 'Testing API from Python',
 'TypeOfItem': 'ReferenceTable',
 'Labels': [],
 'Name': 'PyRefTable'}

## Save RefTable Data

In [25]:
df = df.rename(columns={"F [cm]": "F [m]", "E [ft]": "E [m]"})

In [26]:
# save data and overwrite existing data, meaning that rows with the same 'Entity', 'Timestamp/Date/Time', 'Key' will be overwritten

start_time = time.time()

api.save_ref_table_data(name, df, skip_existing_data = False)

end_time = time.time()
print(f"Elapsed time: {(end_time-start_time)/60}")

Elapsed time: 0.1657450318336487

In [27]:
# df = df.rename(columns={"F": "F [cm]", "E": "E [ft]"})
df = df.rename(columns={col: i for i, col in enumerate(df.columns)})
df

,0,1,2,3,4,5,6,7,8
0,Well 001,2025-01-01 00:00:00,0,0.758688,0.259537,0.015066,0.232888,2.372009,21.393773
1,Well 001,2025-01-01 01:00:00,1,0.540870,0.711250,0.526099,0.787087,0.368429,18.660750
2,Well 001,2025-01-01 02:00:00,2,0.028996,0.039536,0.946708,0.910372,1.694284,27.148022
3,Well 001,2025-01-01 03:00:00,3,0.495759,0.232222,0.594412,0.694344,1.186575,83.505024
4,Well 001,2025-01-01 04:00:00,4,0.398229,0.301194,0.508277,0.872429,0.051103,20.485791
...,...,...,...,...,...,...,...,...,...
995,None,2025-02-11 11:00:00,995,0.226142,0.540866,0.276993,0.076726,0.617016,60.938542
996,None,2025-02-11 12:00:00,996,0.299810,0.035254,0.836530,0.393418,2.567715,32.945636
997,None,2025-02-11 13:00:00,997,0.964502,0.649402,0.099932,0.170256,0.250131,69.789285
998,None,2025-02-11 14:00:00,998,0.635254,0.340741,0.684322,0.561054,1.877994,36.770105
999,None,NaT,999,0.360030,0.328658,0.548452,0.077664,0.892659,18.963076

In [28]:
# save data but keep existing data, meaning that rows with the same 'Entity', 'Timestamp/Date/Time', 'Key' will be not overwritten

start_time = time.time()

api.save_ref_table_data(name, df, skip_existing_data = True)

end_time = time.time()
print(f"Elapsed time: {(end_time-start_time)/60}")

Elapsed time: 0.08156402905782063

## Load RefTable Data

In [29]:
start_time = time.time()

df_loaded = api.load_ref_table_data(name)

end_time = time.time()
print(f"Elapsed time: {(end_time-start_time)/60}")

df_loaded

Elapsed time: 0.07327447334925334

,Entity,Timestamp,Key [ ],A [ ],B [ ],C [ ],D [ ],E [ft],F [cm]
0,Well 001,2025-01-01T00:00:00,0,0.758688,0.259537,0.015066,0.232888,2.372009,21.393773
1,Well 001,2025-01-01T01:00:00,1,0.540870,0.711250,0.526099,0.787087,0.368429,18.660750
2,Well 001,2025-01-01T02:00:00,2,0.028996,0.039536,0.946708,0.910372,1.694284,27.148022
3,Well 001,2025-01-01T03:00:00,3,0.495759,0.232222,0.594412,0.694344,1.186575,83.505024
4,Well 001,2025-01-01T04:00:00,4,0.398229,0.301194,0.508277,0.872429,0.051103,20.485791
...,...,...,...,...,...,...,...,...,...
995,None,2025-02-11T11:00:00,995,0.226142,0.540866,0.276993,0.076726,0.617016,60.938542
996,None,2025-02-11T12:00:00,996,0.299810,0.035254,0.836530,0.393418,2.567715,32.945636
997,None,2025-02-11T13:00:00,997,0.964502,0.649402,0.099932,0.170256,0.250131,69.789285
998,None,2025-02-11T14:00:00,998,0.635254,0.340741,0.684322,0.561054,1.877994,36.770105
999,None,None,999,0.360030,0.328658,0.548452,0.077664,0.892659,18.963076

In [30]:
# load data using filter options
start_time = time.time()

df_loaded = api.load_ref_table_data(name,
                                    date_start=datetime(2025, 1, 1),
                                    date_end=datetime(2025, 1, 10),
                                    columns=["F [cm]", "E [cm]"],
                                    top=10,
                                    all_cols=False,
                                    where="[Entity] = 'Well 001' AND [Key] >= '20'",
                                   )

end_time = time.time()
print(f"Elapsed time: {(end_time-start_time)/60}")

df_loaded

Elapsed time: 0.06965057849884033

     Entity            Timestamp  Key [ ]     F [cm]     E [cm]
0  Well 001  2025-01-01T20:00:00       20  13.448012  11.299581
1  Well 001  2025-01-01T21:00:00       21   5.898684  90.169203
2  Well 001  2025-01-01T22:00:00       22  92.115204  47.709064
3  Well 001  2025-01-01T23:00:00       23  19.768859  60.054484
4  Well 001  2025-01-02T00:00:00       24  77.699293  55.325137
5  Well 001  2025-01-02T01:00:00       25   9.749183  71.444151
6  Well 001  2025-01-02T02:00:00       26  79.512291  70.993481
7  Well 001  2025-01-02T03:00:00       27  56.573704  95.615620
8  Well 001  2025-01-02T04:00:00       28  94.802731   6.343144
9  Well 001  2025-01-02T06:00:00       30  46.542878  64.730326

## Delete RefTable Data

In [31]:
# delete ref table data using filter options
api.delete_ref_table_data(name,
                          entities=["Well 001", None],
                          date_start=datetime(2025,1,1),
                          date_end=datetime(2025,1,10),
                          drop_null_dates=True,
                          where="[Key] > '20'",
                         )

In [32]:
api.load_ref_table_data(name)

,Entity,Timestamp,Key [ ],A [ ],B [ ],C [ ],D [ ],E [ft],F [cm]
0,Well 001,2025-01-01T00:00:00,0,0.758688,0.259537,0.015066,0.232888,2.372009,21.393773
1,Well 001,2025-01-01T01:00:00,1,0.540870,0.711250,0.526099,0.787087,0.368429,18.660750
2,Well 001,2025-01-01T02:00:00,2,0.028996,0.039536,0.946708,0.910372,1.694284,27.148022
3,Well 001,2025-01-01T03:00:00,3,0.495759,0.232222,0.594412,0.694344,1.186575,83.505024
4,Well 001,2025-01-01T04:00:00,4,0.398229,0.301194,0.508277,0.872429,0.051103,20.485791
...,...,...,...,...,...,...,...,...,...
770,None,2025-02-11T11:00:00,995,0.226142,0.540866,0.276993,0.076726,0.617016,60.938542
771,None,2025-02-11T12:00:00,996,0.299810,0.035254,0.836530,0.393418,2.567715,32.945636
772,None,2025-02-11T13:00:00,997,0.964502,0.649402,0.099932,0.170256,0.250131,69.789285
773,None,2025-02-11T14:00:00,998,0.635254,0.340741,0.684322,0.561054,1.877994,36.770105
774,None,None,999,0.360030,0.328658,0.548452,0.077664,0.892659,18.963076

In [33]:
# delete ref table data using keys
api.delete_ref_table_data(name,
                          keys=[
                              ["Well 001", datetime(2025,1,1,1), 1],
                              [None, datetime(2025,2,11,14), 998],
                          ],
                         )

In [34]:
api.load_ref_table_data(name)

,Entity,Timestamp,Key [ ],A [ ],B [ ],C [ ],D [ ],E [ft],F [cm]
0,Well 001,2025-01-01T00:00:00,0,0.758688,0.259537,0.015066,0.232888,2.372009,21.393773
1,Well 001,2025-01-01T02:00:00,2,0.028996,0.039536,0.946708,0.910372,1.694284,27.148022
2,Well 001,2025-01-01T03:00:00,3,0.495759,0.232222,0.594412,0.694344,1.186575,83.505024
3,Well 001,2025-01-01T04:00:00,4,0.398229,0.301194,0.508277,0.872429,0.051103,20.485791
4,Well 001,2025-01-01T05:00:00,5,0.393464,0.478849,0.363851,0.083691,0.514917,31.454020
...,...,...,...,...,...,...,...,...,...
768,None,2025-02-11T10:00:00,994,0.391297,0.526319,0.504198,0.147912,1.029099,8.222715
769,None,2025-02-11T11:00:00,995,0.226142,0.540866,0.276993,0.076726,0.617016,60.938542
770,None,2025-02-11T12:00:00,996,0.299810,0.035254,0.836530,0.393418,2.567715,32.945636
771,None,2025-02-11T13:00:00,997,0.964502,0.649402,0.099932,0.170256,0.250131,69.789285
772,None,None,999,0.360030,0.328658,0.548452,0.077664,0.892659,18.963076

In [35]:
api.delete_ref_table_data(name)